language: rust
rust:
  - stable
script:
  - cargo build --release --manifest-path gitrs_server/Cargo.toml --verbose --all
cache: cargo
branches:
  only:
    - /^\d+\.\d+\.\d+$/
matrix:
  include:
  - os: linux
    env: TARGET=x86_64-unknown-linux-gnu
  - os: osx
    env: TARGET=x86_64-apple-darwin
before_install:
  - nvm install 8
  - nvm use 8
  - npm i -g npm@6.1.0
  - npm ci --prefix ./ci
before_deploy:
  - node ./ci/checkTomlSemver.js
  - node ./ci/buildRelease.js
after_success:
  - node ./ci/checkIsRelease.js && DO_DEPLOY=true || true
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: q+kg5xTmoOK4ZnM4FZI0gh7P1zKCh8VRVdww8ujlAxnKvS/WposkPymxQPD/tvdaIuGMCIQN5sL/C/W0R50GJ9lDNkKA9TmfUjHbmFO7kseFjAPMD2MgaK4bIOS7L7BrmGlFZ8lL71IRr259br20t7SFEWP2OOvbkF0Zzj9ItRUZNmYc/ToGzoIfy8b5fF48OO1OLx+XdtMrUIq3BmqzeAwVQ1SU3H+9e2n5CBXa8Lvod1rCylHleHoN0E/Ko44k/M7TDbydMd4bvTpKdWlrEwtJ5vUBxAS/KoKQyWX9gNttZSTlpKfDgwXKz/WXmdkYb7E3mnHSIFQqfQFCZVOPLSUtj+De1eJd8LTu8F1NgrtV8E7G+fxM+Hy0Ed5ePVXh0i0zT3qWdbN1sSJM9a983a4+p2sEkKlW7wMD4OQ12WIGOdPeqgxqVBRbsalu9pt3zDjs63rnQpv8uQhQQbS2D74kW4KasKFHgf0qDhfLmqjvHZV6OVfFzJH3Hlq356cMRakfVkQ1u4hNS6fzzXiDN+tjxiTvXvUUdiIRctBiey5TKbuqCUyZqDSW2zfhBQzGvlRlNQfZsfjOrCM5nelxkXDfA7lcuwDCuAVMb0tgchW7D7dxkz6UHmYro5r2pkebwf3zIqA1Q7J87laWtcj3HvPl0SegH13+brORycIyYQo=
  file: "$TARGET.zip"
  on:
    repo: implausible/git-rs
    tags: true
    condition: "$DO_DEPLOY"
